---
- name: Create Pi-hole folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/pi-hole"
    state: directory
    mode: 0755
  become: false

- name: Create Unbound folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/pi-hole/etc-unbound"
    state: directory
    mode: 0755
  become: false

- name: Create dnsmasq folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/pi-hole/etc-dnsmasq.d"
    state: directory
    mode: 0755
  become: false

- name: Copy unbound.conf template to Pi.
  ansible.builtin.template:
    src: templates/unbound.conf.j2
    dest: "{{ config_dir }}/pi-hole/etc-unbound/unbound.conf"
    mode: '0644'
  become: false
  notify: Restart pi-hole

- name: Copy Pi-hole docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/pi-hole-docker-compose.yml.j2
    dest: "{{ config_dir }}/pi-hole/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart pi-hole

- name: Copy dnsmasq config template to Pi.
  ansible.builtin.template:
    src: templates/pi-hole-custom-dns-config.conf.j2
    dest: "{{ config_dir }}/pi-hole/etc-dnsmasq.d/custom-dns-config.conf"
    mode: '0644'
  become: false
  notify: Restart pi-hole

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Pi-hole is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pi-hole/"
    build: false
  become: false
